"""Capital-structure object model.

The model is built around legal *entities*, not just lien ranks, so that
**structural subordination** is explicit: an operating company's (opco) debt is
satisfied from that opco's value *before* any value flows up to a holding
company (holdco), regardless of the stated lien on the holdco paper. This is the
single most common thing hand-built waterfalls get wrong.

Within an entity, claims are paid by absolute priority:
    admin/fees  ->  secured (by lien rank, sharing the entity's value)  ->
    unsecured (pro rata, including secured deficiency claims)  ->  equity (residual)

The residual equity of a subsidiary becomes an asset of its parent.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

# Sentinel lien rank for unsecured claims. Any tranche with secured=False is
# treated as unsecured regardless of this value; it exists so unsecured paper
# sorts after all secured paper when we order by priority.
UNSECURED = 99


@dataclass
class Entity:
    """A legal entity in the corporate structure.

    ev_share: the fraction of *consolidated* enterprise value generated by this
        entity's own operations (its share of the pie before any upstreaming).
        Shares across all entities should sum to ~1.0.
    parent: the name of this entity's parent, or None if it sits at the top of
        the structure (the holdco / ultimate equity owner).
    """

    name: str
    ev_share: float
    parent: Optional[str] = None


@dataclass
class Tranche:
    """A debt claim sitting at a specific entity.

    lien_rank: 1 = first lien, 2 = second lien, ... Lower is more senior. Tranches
        sharing a lien rank are pari passu and share pro rata. Ignored when
        secured=False (use UNSECURED for readability).
    secured: if True, the tranche is secured by the entity's value in lien order
        (all-asset pledge assumption). If False, it is a general unsecured claim
        at that entity and shares the residual pro rata with secured deficiencies.
    preferred: preferred stock - paid after all debt at the entity, before common
        equity. Implies secured=False.
    """

    name: str
    entity: str
    face: float
    lien_rank: int = UNSECURED
    secured: bool = False
    preferred: bool = False
    coupon: float = 0.0               # decimal (0.06 = 6%); drives accrued interest
    maturity: Optional[str] = None    # informational only
    accrued_interest: float = 0.0     # explicit $ accrued to petition; else derived from coupon
    make_whole: float = 0.0           # explicit $ make-whole / prepayment premium (default: none)
    collateral_value: Optional[float] = None  # caps the secured claim (§506); deficiency joins
                                              # the unsecured pool. None = all-asset pledge.
    subordinated_to: Optional[str] = None     # contractual subordination: this tranche's recovery
                                              # is redirected to the named tranche until it is
                                              # paid in full (Moyer ch. 7 subrogation)

    def __post_init__(self) -> None:
        if self.face < 0:
            raise ValueError(f"{self.name}: face must be non-negative")
        if self.accrued_interest < 0 or self.make_whole < 0:
            raise ValueError(f"{self.name}: accrued_interest / make_whole must be non-negative")
        if self.collateral_value is not None and self.collateral_value < 0:
            raise ValueError(f"{self.name}: collateral_value must be non-negative")
        if self.preferred:
            self.secured = False
        if not self.secured:
            self.lien_rank = UNSECURED

    def accrued(self, accrual_years: float = 0.0) -> float:
        """Accrued interest in the allowed claim: an explicit amount if set, else
        face × coupon × accrual_years (accrual_years = coupon-periods to petition)."""
        if self.accrued_interest:
            return self.accrued_interest
        return self.face * self.coupon * max(accrual_years, 0.0)

    def claim(self, accrual_years: float = 0.0) -> float:
        """The allowed claim that shares in the waterfall: principal + accrued + make-whole."""
        return self.face + self.accrued(accrual_years) + self.make_whole


@dataclass
class CapitalStructure:
    """A company's full capital structure plus the legal-entity tree.

    admin_fees: estimated administrative / professional-fee claims of the estate
        (advisors, lawyers, trustees). Modeled as the most-senior estate cost,
        deducted from enterprise value before anything is allocated. Outsiders
        routinely underestimate these; they run materially higher than expected.
    """

    name: str
    entities: list[Entity]
    tranches: list[Tranche]
    admin_fees: float = 0.0
    admin_pct: float = 0.0            # admin/deadweight cost as a fraction of EV, deducted
                                      # before distribution (Moyer: outsiders underestimate;
                                      # UI defaults 7%). Stacks with the $ admin_fees.

    def __post_init__(self) -> None:
        self.validate()

    # -- lookups -----------------------------------------------------------
    def entity_map(self) -> dict[str, Entity]:
        return {e.name: e for e in self.entities}

    def tranches_at(self, entity_name: str) -> list[Tranche]:
        return [t for t in self.tranches if t.entity == entity_name]

    # -- ordering ----------------------------------------------------------
    def post_order(self) -> list[str]:
        """Entities ordered children-before-parents (leaves/opcos first).

        This is the order in which entity waterfalls must run: a subsidiary must
        be fully resolved before its residual equity can be handed up to the
        parent.
        """
        emap = self.entity_map()
        children: dict[str, list[str]] = {e.name: [] for e in self.entities}
        for e in self.entities:
            if e.parent is not None:
                children[e.parent].append(e.name)

        order: list[str] = []
        visiting: set[str] = set()
        done: set[str] = set()

        def visit(name: str) -> None:
            if name in done:
                return
            if name in visiting:
                raise ValueError(f"Cycle detected in entity tree at '{name}'")
            visiting.add(name)
            for child in children[name]:
                visit(child)
            visiting.discard(name)
            done.add(name)
            order.append(name)

        roots = [e.name for e in self.entities if e.parent is None]
        for r in roots:
            visit(r)
        # include any entity not reachable from a root (defensive)
        for e in self.entities:
            visit(e.name)
        return order

    def priority_order(self) -> list[str]:
        """Tranche names from most-senior to most-junior across the whole
        structure (structural priority, then lien rank, then unsecured).

        Used to locate the fulcrum security and to present results top-down.
        """
        names: list[str] = []
        for ent in self.post_order():  # opcos before holdco => more senior first
            ts = self.tranches_at(ent)
            secured = sorted([t for t in ts if t.secured], key=lambda t: t.lien_rank)
            unsecured = [t for t in ts if not t.secured and not t.preferred]
            preferred = [t for t in ts if t.preferred]
            names.extend(t.name for t in secured)
            names.extend(t.name for t in unsecured)
            names.extend(t.name for t in preferred)
        return names

    # -- validation --------------------------------------------------------
    def validate(self) -> None:
        names = [e.name for e in self.entities]
        if len(names) != len(set(names)):
            raise ValueError("Duplicate entity names")
        tnames = [t.name for t in self.tranches]
        if len(tnames) != len(set(tnames)):
            raise ValueError("Duplicate tranche names")

        emap = set(names)
        for e in self.entities:
            if e.parent is not None and e.parent not in emap:
                raise ValueError(f"Entity '{e.name}' references unknown parent '{e.parent}'")
            if e.ev_share < 0:
                raise ValueError(f"Entity '{e.name}' has negative ev_share")
        for t in self.tranches:
            if t.entity not in emap:
                raise ValueError(f"Tranche '{t.name}' references unknown entity '{t.entity}'")

        total_share = sum(e.ev_share for e in self.entities)
        if abs(total_share - 1.0) > 1e-6:
            raise ValueError(
                f"Entity ev_share must sum to 1.0 (got {total_share:.4f}). "
                "These are shares of consolidated enterprise value."
            )
        if self.admin_fees < 0:
            raise ValueError("admin_fees must be non-negative")
        if not 0.0 <= self.admin_pct < 0.5:
            raise ValueError("admin_pct must be in [0, 0.5)")
        tmap = {t.name: t for t in self.tranches}
        for t in self.tranches:
            if t.subordinated_to is not None:
                target = tmap.get(t.subordinated_to)
                if target is None:
                    raise ValueError(
                        f"Tranche '{t.name}' subordinated to unknown tranche '{t.subordinated_to}'")
                if target.entity != t.entity:
                    raise ValueError(
                        f"Tranche '{t.name}' subordinated to '{t.subordinated_to}' at a different "
                        "entity — contractual subordination only reroutes within an entity")
                if target.name == t.name:
                    raise ValueError(f"Tranche '{t.name}' cannot be subordinated to itself")
        # post_order also checks for cycles
        self.post_order()

    def total_face(self) -> float:
        return sum(t.face for t in self.tranches)
